### ISSUE TITLE
Calendar System Can Read Our ics File

### ISSUE THREAD

**Issue by chriswon98** [Team-Pickled-Plums/Gregory#3]

**Comment by matthew-schultz** [comment]
Requirements from [the spring 2020 calendar pdf](https://laulima.hawaii.edu/access/content/group/MAN.85453.202030/Event%20planner/Spring2020CalendarPDF.pdf) in laulima:

At least minimally functioning code that does something: You must demonstrate code, even if it is just print statements, that generates a .ics file for a simple, single occurrence event: Study for exam, 10am-1pm HST, 13 March 2020, in Hamilton Library. 

You must then demonstrate that the calendar program of your choice (say, google calendar) successfully reads and processes your .ics file.

**Comment by chriswon98** [comment]
Testing system: Google Calendar
